### PR TITLE
resolve dna values from process.env

### PR DESCRIPTION
**Pull request by multi**
needed for easy containerization. docker uses heavily env properties ...

it will resolve dna values from `process.env` which starts with `@process.env`

Cheers!

### CODE REVIEW

**Comment by VanTanev** [comment]
@multi `jasmine-node` is not the official Jasmine module, and is abandoned. The official one is `jasmine-npm`.

But, please, use mocha. Jasmine is ill-suited to the backend :)

**Comment by multi** [comment]
@VanTanev I know. It's not my choice, it's @outbounder. about mocha, i prefer tape ;)

**Comment by outbounder** [comment]
@multi @VanTanev I believe the best solution for this feature would be to be separated module/implementation, thus keep it simple and doing only one job but good enough. Increasing the scope of the current organic-dna-resolvereferences implementation makes it too heavy for mine taste

:heavy_plus_sign: 

in the new module (a separate repo & etc) you'll be able to use whatever testing framework you want :P

**Comment by multi** [comment]
@outbounder okay

**Pull request closed without merging**
